services:
  mysql_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3310:3306"
    volumes:
      - e-commerce_data:/var/lib/mysql

volumes:
  e-commerce_data: